name: Deployment Workflow
on: 
    workflow_call:
        inputs:
            artificat-name:
                description: Name of the build artifact to deploy
                required: false
                default: dist-files
                type: string
        outputs:
            result:
                description: 'result of deployment'
                value: ${{ jobs.deploy.outputs.outcome}}
        secrets:
            some-secret:
                description: 'A secret for deployment'
                required: false
jobs:
    deploy:
        outputs:
            outcome: ${{ steps.set-result.outputs.step-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Download Build Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: ${{ inputs.artificat-name }}
            - name: List Downloaded Files
              run: ls -la
            - name: Output Deployment Message
              run: echo "Deploying application..."
            - name: Set Deployment Result
              id: set-result
              run: echo "step-result=success" >> $GITHUB_OUTPUT